### ISSUE TITLE
Channel not found for Trades Error code: "405", message:"Channel not found"

### ISSUE THREAD

**Issue by ByronAP** [lvcn1/ws-client-examples#9]
Using the C# example trying to get trades on BTC/USD I get

> Error code: "405", message:"Channel not found"

**OnOpen method:** 
`WsClient_Subscribe(new TradeParams("BTC/USD"));`

**Subscribe method:** 
`var tradeParams = (TradeParams) param;
                    var message = new SubscribeTradeChannelRequest()
                    {
                        CurrencyPair = tradeParams.symbol
                    };
                    meta.RequestType = WsRequestMetaData.WsRequestMsgType.SubscribeTrade;`

**Full output:**
>Status: Connected
Error code: "405", message:"Channel not found"
Status: Disconnected
Press Enter to exit
8/31/2018 9:34:10 PM|Fatal|<>c__DisplayClass48_0.<ReadBytesAsync>b__0|System.ObjectDisposedException: Cannot access a disposed object.
                           Object name: 'SslStream'.
                              at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
                              at System.Net.Security.SslState.get_SecureStream()
                              at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
                              at WebSocketSharp.Ext.<>c__DisplayClass48_0.<ReadBytesAsync>b__0(IAsyncResult ar)

**Comment by ByronAP** [comment]
upon further inspection, it seems trades do not work at all.

In JS I get the following output:

> ws-client-example.js:11 Connection established.
> ws-client-example.js:483 data received 
> ws-client-example.js:670 channel subscribed: {"channelType":"trade","currencyPair":"BTC/USD"}
> ws-client-example.js:483 data received 
> ws-client-example.js:483 data received 
> ws-client-example.js:483 data received 
> ws-client-example.js:483 data received 
> ws-client-example.js:773 Connection closed
> ws-client-example.js:477 Connection failure
> ws-client-example.js:479 Code: 1006 reason:

**Comment by lvcn1** [comment]
Hello!
I added a subscription to the TradeСhannel in the example for c-sharp.
I hope this helps you.
